package it.seat.visualzoom.player;

public interface IconConstants {
	static final String FORECAST_DIR = "icons/forecast/";
	public static final String SOLE = FORECAST_DIR + "01.png";
	public static final String SOLE_NUVOLETTA = FORECAST_DIR + "02.png";
	public static final String SOLE_NUVOLA1 = FORECAST_DIR + "03.png";
	public static final String SOLE_NUVOLA2 = FORECAST_DIR + "04.png";
	public static final String SOLE_AURA = FORECAST_DIR + "05.png";
	public static final String SOLE_ALTO_NUVOLA = FORECAST_DIR + "06.png";
	public static final String NUVOLA1 = FORECAST_DIR + "07.png";
	public static final String NUVOLA2 = FORECAST_DIR + "08.png";
	public static final String NEBBIA = FORECAST_DIR + "11.png";
	public static final String PIOGGIA = FORECAST_DIR + "12.png";
	public static final String SOLE_PIOGGE = FORECAST_DIR + "13.png";
	public static final String SOLE_PIOGGIA = FORECAST_DIR + "14.png";
	public static final String FULMINE = FORECAST_DIR + "15.png";
	public static final String SOLE_FULMINE1 = FORECAST_DIR + "16.png";
	public static final String SOLE_FULMINE2 = FORECAST_DIR + "17.png";
	public static final String PIOGGE = FORECAST_DIR + "18.png";
	public static final String NEVE = FORECAST_DIR + "19.png";
	public static final String SOLE_NEVE1 = FORECAST_DIR + "20.png";
	public static final String SOLE_NEVE2 = FORECAST_DIR + "21.png";
	public static final String NEVI = FORECAST_DIR + "22.png";
	public static final String SOLE_NEVI = FORECAST_DIR + "23.png";
	public static final String GRANDINE = FORECAST_DIR + "24.png";
	public static final String PALLE_AZZURRE = FORECAST_DIR + "25.png";
	public static final String PIOGGE_GRANDINE = FORECAST_DIR + "26.png";
	public static final String NEVISCHIO = FORECAST_DIR + "29.png";
	public static final String TEMP_MASSIMA = FORECAST_DIR + "30.png";
	public static final String TEMP_MINIMA = FORECAST_DIR + "31.png";
	public static final String VENTO = FORECAST_DIR + "32.png";
	public static final String LUNA = FORECAST_DIR + "33.png";
	public static final String LUNA_NUVOLETTA = FORECAST_DIR + "34.png";
	public static final String LUNA_NUVOLA1 = FORECAST_DIR + "35.png";
	public static final String LUNA_NUVOLA2 = FORECAST_DIR + "36.png";
	public static final String LUNA_AURA = FORECAST_DIR + "37.png";
	public static final String LUNA_ALTA_NUVOLA = FORECAST_DIR + "38.png";
	public static final String LUNA_PIOGGIA = FORECAST_DIR + "39.png";
	public static final String LUNA_PIOGGE = FORECAST_DIR + "40.png";
	public static final String LUNA_FULMINE = FORECAST_DIR + "41.png";
	public static final String LUNA_FULMINI = FORECAST_DIR + "42.png";
	public static final String LUNA_NEVE = FORECAST_DIR + "43.png";
	public static final String LUNA_NEVI = FORECAST_DIR + "44.png";
	public static final String BOH = FORECAST_DIR + "swa.png";
}
